import React, { useState } from 'react';
import { DiscordIcon } from '../components/Icons';
import { 
  MessageSquare, 
  Mail, 
  Gamepad2, 
  ChevronDown, 
  ChevronUp, 
  HelpCircle, 
  Clock, 
  CreditCard, 
  ShieldAlert,
  ArrowRight,
  Info
} from 'lucide-react';

interface FAQItemProps {
  question: string;
  answer: React.ReactNode;
  category: string;
}

const FAQItem: React.FC<FAQItemProps> = ({ question, answer, category }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="border border-white/5 bg-white/[0.01] hover:bg-white/[0.02] rounded-2xl overflow-hidden transition-all duration-300">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full p-5 text-left flex justify-between items-center gap-4 focus:outline-none"
      >
        <div className="space-y-1">
          <span className="text-[10px] font-bold text-mc-orange uppercase tracking-wider">{category}</span>
          <h4 className="text-white font-medium text-sm md:text-base leading-snug">{question}</h4>
        </div>
        <div className={`p-2 rounded-lg bg-white/5 text-gray-400 transition-transform duration-300 ${isOpen ? 'rotate-180 text-white' : ''}`}>
          <ChevronDown size={18} />
        </div>
      </button>
      
      {isOpen && (
        <div className="px-5 pb-5 pt-1 text-gray-300 text-sm leading-relaxed border-t border-white/5 bg-black/10 animate-fade-in">
          {answer}
        </div>
      )}
    </div>
  );
}

export default function Support() {
  const supportChannels = [
    {
      title: 'Discord Support Tickets',
      description: 'The fastest way to get help with billing, ranks, crates, or server appeals. Our moderation team handles tickets 24/7.',
      icon: <MessageSquare size={24} className="text-[#5865F2]" />,
      actionText: 'Open a Ticket',
      link: 'https://discord.gg/GDTsV7ttJZ',
      color: 'border-[#5865F2]/20 hover:border-[#5865F2]/40',
      badge: 'Fast Response',
      isDiscord: true
    },
    {
      title: 'Email Assistance',
      description: 'For business inquiries, complex billing issues, or administrative concerns. Write to us directly.',
      icon: <Mail size={24} className="text-mc-orange" />,
      actionText: 'Send an Email',
      link: 'mailto:Vixelbhai57@gmail.com',
      color: 'border-mc-orange/20 hover:border-mc-orange/40',
      badge: '24-48 Hours'
    },
    {
      title: 'In-Game Support',
      description: 'Need help instantly inside Vixel Network? Use our official in-game commands to alert online staff members.',
      icon: <Gamepad2 size={24} className="text-mc-purple" />,
      actionText: 'View Server Commands',
      link: '#commands',
      color: 'border-mc-purple/20 hover:border-mc-purple/40',
      badge: 'Live Support'
    }
  ];

  const faqs = [
    {
      category: 'Payments & Ranks',
      question: "I submitted my payment but haven't received my rank/crate key yet?",
      answer: (
        <p>
          Ranks and Keys are credited after manual UTR verification. This typically takes <strong>5 to 15 minutes</strong>. 
          Make sure you submitted the correct 12-digit UTR/Reference ID from Google Pay, PhonePe, or Paytm. 
          If your purchase is still pending after 30 minutes, please open a support ticket on our 
          <a href="https://discord.gg/GDTsV7ttJZ" target="_blank" rel="noopener noreferrer" className="text-mc-orange underline mx-1 font-semibold">Discord Server</a> 
          with your transaction screenshot and the tracking code generated by our check-out modal.
        </p>
      )
    },
    {
      category: 'Billing Methods',
      question: "Which payment methods do you officially accept?",
      answer: (
        <p>
          We currently support all major UPI platforms including <strong>Google Pay (GPay), PhonePe, Paytm, and BHIM UPI</strong>. 
          You can make direct transfers via the official UPI QR codes displayed in our checkout popup.
        </p>
      )
    },
    {
      category: 'In-Game Support',
      question: "How do I report a hacker or bug in-game?",
      answer: (
        <p>
          To report a player in real-time, use the in-game command: <code className="bg-white/5 px-1.5 py-0.5 rounded text-mc-orange font-mono">/report &lt;username&gt; &lt;reason&gt;</code>. 
          To report server exploits, item dupes, or client bugs, please open a secure ticket under the <strong>#bug-reports</strong> channel on our Discord to prevent abuse and claim rewards.
        </p>
      )
    },
    {
      category: 'Account Safety',
      question: "Can I transfer my rank/crate keys to another Minecraft account?",
      answer: (
        <p>
          Rank and item transfers are strictly handled on a case-by-case basis (e.g. if you officially changed your premium Minecraft username). 
          To request a migration, you must join our Discord, open an administrative ticket, and provide valid proof of ownership for both accounts.
        </p>
      )
    },
    {
      category: 'Community Moderation',
      question: "I was falsely banned or muted. How do I appeal?",
      answer: (
        <p>
          All ban and mute appeals are processed exclusively through our support tickets. 
          Join our Discord, go to the #appeals channel, and open a ticket. Avoid messaging individual staff members on DM as it will slow down your request.
        </p>
      )
    }
  ];

  const serverCommands = [
    { cmd: '/helpop <message>', desc: 'Directly send a message to all online staff members for urgent help.' },
    { cmd: '/report <player> <reason>', desc: 'Report a rule breaker or a hacker to online moderators.' },
    { cmd: '/discord', desc: 'Get our official invitation link in-game to sync your account.' },
    { cmd: '/rules', desc: 'Read Vixel Network server rules to avoid infractions and mutes.' }
  ];

  return (
    <div className="py-12 px-4 max-w-6xl mx-auto space-y-16 animate-fade-in">
      {/* Hero Header */}
      <div className="text-center space-y-4">
        <h1 className="text-4xl md:text-5xl font-display font-bold text-white tracking-tight">
          Support <span className="text-transparent bg-clip-text bg-gradient-to-r from-mc-orange to-mc-purple">Hub</span>
        </h1>
        <p className="text-gray-400 font-medium max-w-xl mx-auto text-sm md:text-base">
          Have questions about your purchase, ranks, or in-game gameplay? Let's get you sorted out immediately.
        </p>
      </div>

      {/* Support Options Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {supportChannels.map((channel, idx) => (
          <div 
            key={idx} 
            className={`bg-white/[0.02] backdrop-blur-md rounded-3xl p-6 border ${channel.color} flex flex-col justify-between transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-black/20`}
          >
            <div>
              <div className="flex justify-between items-start mb-6">
                <div className="p-3 bg-white/5 rounded-2xl border border-white/5">
                  {channel.icon}
                </div>
                <span className="text-[10px] font-bold text-gray-400 bg-white/5 border border-white/5 px-2.5 py-1 rounded-full uppercase tracking-wider">
                  {channel.badge}
                </span>
              </div>
              <h3 className="text-lg font-display font-bold text-white mb-2">{channel.title}</h3>
              <p className="text-xs text-gray-400 leading-relaxed mb-6">{channel.description}</p>
            </div>

            {channel.isDiscord ? (
              <a 
                href={channel.link}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full py-3 rounded-xl font-bold text-xs text-white bg-[#5865F2] hover:bg-[#4752C4] transition-colors flex items-center justify-center gap-2"
              >
                <DiscordIcon size={16} />
                {channel.actionText}
              </a>
            ) : (
              <a 
                href={channel.link}
                className="w-full py-3 rounded-xl font-bold text-xs text-white bg-white/5 hover:bg-white/10 border border-white/5 hover:border-white/10 transition-colors flex items-center justify-center gap-1.5 group"
              >
                {channel.actionText}
                <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
              </a>
            )}
          </div>
        ))}
      </div>

      {/* FAQ Section */}
      <div className="space-y-6">
        <div className="flex items-center gap-2.5 pb-2 border-b border-white/5 max-w-md">
          <HelpCircle className="text-mc-orange" size={22} />
          <h2 className="text-xl font-display font-semibold text-white">Frequently Asked Questions</h2>
        </div>
        
        <div className="grid grid-cols-1 gap-4 max-w-4xl">
          {faqs.map((faq, i) => (
            <FAQItem 
              key={i}
              category={faq.category}
              question={faq.question}
              answer={faq.answer}
            />
          ))}
        </div>
      </div>

      {/* In-Game Support Commands */}
      <div id="commands" className="bg-gradient-to-br from-mc-orange/5 to-mc-purple/5 border border-white/5 rounded-3xl p-6 md:p-8 space-y-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1">
            <h3 className="text-lg font-display font-bold text-white flex items-center gap-2">
              <Gamepad2 className="text-mc-purple" size={20} />
              In-Game Support Commands
            </h3>
            <p className="text-xs text-gray-400">Run these commands directly inside the Minecraft lobby or survival server.</p>
          </div>
          <div className="inline-flex items-center gap-2 bg-black/40 border border-white/5 p-2 px-4 rounded-xl text-[11px] text-gray-300">
            <Info size={14} className="text-mc-orange shrink-0" />
            <span>Ensure you have an active network connection</span>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {serverCommands.map((command, idx) => (
            <div key={idx} className="bg-black/30 border border-white/5 p-4 rounded-2xl flex flex-col justify-center space-y-1.5 hover:border-white/10 transition-colors">
              <code className="text-xs font-mono font-bold text-mc-orange">{command.cmd}</code>
              <p className="text-xs text-gray-400 leading-normal">{command.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
